In [1]:
import pandas as pd
!python -m pip install wordcloud
!python -m pip install textblob
from textblob import TextBlob
from wordcloud import WordCloud
import numpy as np
import re
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

Requirement already satisfied: wordcloud in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (1.8.1)
Requirement already satisfied: matplotlib in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from wordcloud) (3.4.3)
Requirement already satisfied: numpy>=1.6.1 in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from wordcloud) (1.20.3)
Requirement already satisfied: pillow in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from wordcloud) (8.4.0)
Requirement already satisfied: cycler>=0.10 in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->wordcloud) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from matplotlib->wordcloud) (3.0.4)
Requirement already satisfied: six in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from cycler>=0.10->matplotlib->wordcloud) (1.16.0)
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/Users/ruby/opt/anaconda3/bin/python -m pip install --upgrade pip' command.
Requirement already satisfied: textblob in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (0.17.1)
Requirement already satisfied: nltk>=3.1 in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from textblob) (3.6.5)
Requirement already satisfied: click in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from nltk>=3.1->textblob) (8.0.3)
Requirement already satisfied: joblib in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from nltk>=3.1->textblob) (1.1.0)
Requirement already satisfied: regex>=2021.8.3 in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from nltk>=3.1->textblob) (2021.8.3)
Requirement already satisfied: tqdm in /Users/ruby/opt/anaconda3/lib/python3.9/site-packages (from nltk>=3.1->textblob) (4.62.3)
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/Users/ruby/opt/anaconda3/bin/python -m pip install --upgrade pip' command.

In [2]:
df = pd.read_csv('timeline_tweets_ukraine_week_past.csv')
df["temp"] = df['Time']
df["Time"] = df['Tweet']
df["Tweet"] = df["temp"]
del df["temp"]
df.to_csv('timeline_tweets_ukraine_week_past2.csv', index=False)

In [6]:
#merging dataframe2
#we already imported pandas up above
# merging multiple csv files

csv_files = [
    'timeline_tweets_ukraine_week_past2.csv',
    'timeline_tweets_putin_1000_without_retweets.csv'
]
df_merged2 = pd.concat(map(pd.read_csv, csv_files), ignore_index=True)
print(df_merged2)

      Unnamed: 0             user  \
0              0         Judgenap
1              1   kiraincongress
2              2         nexta_tv
3              3          LSaczak
4              4      ReArtistron
...          ...              ...
9211         995      hasibabibi1
9212         996    vanderschlong
9213         997      Villain1982
9214         998  PeaceLover07405
9215         999    HilliusGlitch

                                                  Tweet  \
0     Putin did NOT start the Ukraine War\nCol Doug ...
1     #Pentagon may double the supply of #Himars MLR...
2     The #Russian Ministry of Emergency Situations ...
3     RT @officejjsmart: This is what it looks like ...
4     RT @VivianAaron5: Check out this new framed pr...
...                                                 ...
9211  RT @97Maria_Hydra: @ZelenskyyUa @kajakallas Se...
9212  @DSSdeltona @WhiteHouse @JoeBiden #Putin was h...
9213  @vonderleyen @EU_Commission What a pile of hor...
9214  @AZmilitary1 If we stop supporting #Ukraine, #...
9215  Oh deary deary me! ðŸ˜¬\nI wonder if the Germans ...

                           Time
0     2022-06-21 19:42:58+00:00
1     2022-06-20 07:00:00+00:00
2     2022-06-20 06:31:36+00:00
3     2022-06-21 23:59:49+00:00
4     2022-06-21 23:58:13+00:00
...                         ...
9211  2022-06-22 15:00:31+00:00
9212  2022-06-22 14:59:20+00:00
9213  2022-06-22 14:58:11+00:00
9214  2022-06-22 14:56:51+00:00
9215  2022-06-22 14:54:59+00:00

[9216 rows x 4 columns]

In [7]:
df_merged2['Time']

0       2022-06-21 19:42:58+00:00
1       2022-06-20 07:00:00+00:00
2       2022-06-20 06:31:36+00:00
3       2022-06-21 23:59:49+00:00
4       2022-06-21 23:58:13+00:00
                  ...
9211    2022-06-22 15:00:31+00:00
9212    2022-06-22 14:59:20+00:00
9213    2022-06-22 14:58:11+00:00
9214    2022-06-22 14:56:51+00:00
9215    2022-06-22 14:54:59+00:00
Name: Time, Length: 9216, dtype: object

In [8]:
#it does string replace and splicing

df_merged2['Time']= df_merged2['Time'].apply(lambda x:x.replace(':', '-')[:-6]) #last part is to remove the extra miliseconds
df_merged2['Time']

0       2022-06-21 19-42-58
1       2022-06-20 07-00-00
2       2022-06-20 06-31-36
3       2022-06-21 23-59-49
4       2022-06-21 23-58-13
               ...
9211    2022-06-22 15-00-31
9212    2022-06-22 14-59-20
9213    2022-06-22 14-58-11
9214    2022-06-22 14-56-51
9215    2022-06-22 14-54-59
Name: Time, Length: 9216, dtype: object

In [9]:
#column reshuffling #created.a new column and put all the values in the time column here
df_merged2["DateTimeStr"] = df_merged2['Time']
print(df_merged2)

      Unnamed: 0             user  \
0              0         Judgenap
1              1   kiraincongress
2              2         nexta_tv
3              3          LSaczak
4              4      ReArtistron
...          ...              ...
9211         995      hasibabibi1
9212         996    vanderschlong
9213         997      Villain1982
9214         998  PeaceLover07405
9215         999    HilliusGlitch

                                                  Tweet                 Time  \
0     Putin did NOT start the Ukraine War\nCol Doug ...  2022-06-21 19-42-58
1     #Pentagon may double the supply of #Himars MLR...  2022-06-20 07-00-00
2     The #Russian Ministry of Emergency Situations ...  2022-06-20 06-31-36
3     RT @officejjsmart: This is what it looks like ...  2022-06-21 23-59-49
4     RT @VivianAaron5: Check out this new framed pr...  2022-06-21 23-58-13
...                                                 ...                  ...
9211  RT @97Maria_Hydra: @ZelenskyyUa @kajakallas Se...  2022-06-22 15-00-31
9212  @DSSdeltona @WhiteHouse @JoeBiden #Putin was h...  2022-06-22 14-59-20
9213  @vonderleyen @EU_Commission What a pile of hor...  2022-06-22 14-58-11
9214  @AZmilitary1 If we stop supporting #Ukraine, #...  2022-06-22 14-56-51
9215  Oh deary deary me! ðŸ˜¬\nI wonder if the Germans ...  2022-06-22 14-54-59

              DateTimeStr
0     2022-06-21 19-42-58
1     2022-06-20 07-00-00
2     2022-06-20 06-31-36
3     2022-06-21 23-59-49
4     2022-06-21 23-58-13
...                   ...
9211  2022-06-22 15-00-31
9212  2022-06-22 14-59-20
9213  2022-06-22 14-58-11
9214  2022-06-22 14-56-51
9215  2022-06-22 14-54-59

[9216 rows x 5 columns]

In [10]:
from datetime import datetime
_format = '%Y-%m-%d %H-%M-%S'
dt_func = lambda dt_str: datetime.strptime(str(dt_str), _format) #convert datetime str to datetime obj
time_func = lambda dt_str: datetime.strptime(str(dt_str), _format).time() #convert datetime str to time
date_func = lambda dt_str: datetime.strptime(str(dt_str), _format).date() #convert datetime str to date
df_merged2["Date"]= df_merged2["DateTimeStr"].apply(dt_func)
df_merged2["Time"]= df_merged2["DateTimeStr"].apply(dt_func)

In [11]:
print(df_merged2["Date"],"\n"*2)
print(df_merged2["Time"],"\n"*2)

0      2022-06-21 19:42:58
1      2022-06-20 07:00:00
2      2022-06-20 06:31:36
3      2022-06-21 23:59:49
4      2022-06-21 23:58:13
               ...
9211   2022-06-22 15:00:31
9212   2022-06-22 14:59:20
9213   2022-06-22 14:58:11
9214   2022-06-22 14:56:51
9215   2022-06-22 14:54:59
Name: Date, Length: 9216, dtype: datetime64[ns]


0      2022-06-21 19:42:58
1      2022-06-20 07:00:00
2      2022-06-20 06:31:36
3      2022-06-21 23:59:49
4      2022-06-21 23:58:13
               ...
9211   2022-06-22 15:00:31
9212   2022-06-22 14:59:20
9213   2022-06-22 14:58:11
9214   2022-06-22 14:56:51
9215   2022-06-22 14:54:59
Name: Time, Length: 9216, dtype: datetime64[ns]

In [12]:
df_merged2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   9216 non-null   int64
 1   user         9216 non-null   object
 2   Tweet        9216 non-null   object
 3   Time         9216 non-null   datetime64[ns]
 4   DateTimeStr  9216 non-null   object
 5   Date         9216 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 432.1+ KB

In [13]:
column = ['DateTimeStr']
df_merged2.drop(column, axis=1, inplace=True)
df_merged2

,Unnamed: 0,user,Tweet,Time,Date
0,0,Judgenap,Putin did NOT start the Ukraine War\nCol Doug ...,2022-06-21 19:42:58,2022-06-21 19:42:58
1,1,kiraincongress,#Pentagon may double the supply of #Himars MLR...,2022-06-20 07:00:00,2022-06-20 07:00:00
2,2,nexta_tv,The #Russian Ministry of Emergency Situations ...,2022-06-20 06:31:36,2022-06-20 06:31:36
3,3,LSaczak,RT @officejjsmart: This is what it looks like ...,2022-06-21 23:59:49,2022-06-21 23:59:49
4,4,ReArtistron,RT @VivianAaron5: Check out this new framed pr...,2022-06-21 23:58:13,2022-06-21 23:58:13
...,...,...,...,...,...
9211,995,hasibabibi1,RT @97Maria_Hydra: @ZelenskyyUa @kajakallas Se...,2022-06-22 15:00:31,2022-06-22 15:00:31
9212,996,vanderschlong,@DSSdeltona @WhiteHouse @JoeBiden #Putin was h...,2022-06-22 14:59:20,2022-06-22 14:59:20
9213,997,Villain1982,@vonderleyen @EU_Commission What a pile of hor...,2022-06-22 14:58:11,2022-06-22 14:58:11
9214,998,PeaceLover07405,"@AZmilitary1 If we stop supporting #Ukraine, #...",2022-06-22 14:56:51,2022-06-22 14:56:51
9215,999,HilliusGlitch,Oh deary deary me! ðŸ˜¬\nI wonder if the Germans ...,2022-06-22 14:54:59,2022-06-22 14:54:59

In [14]:
df_merged2.drop(df_merged2.columns[[0]], axis=1, inplace=True)
df_merged2

,user,Tweet,Time,Date
0,Judgenap,Putin did NOT start the Ukraine War\nCol Doug ...,2022-06-21 19:42:58,2022-06-21 19:42:58
1,kiraincongress,#Pentagon may double the supply of #Himars MLR...,2022-06-20 07:00:00,2022-06-20 07:00:00
2,nexta_tv,The #Russian Ministry of Emergency Situations ...,2022-06-20 06:31:36,2022-06-20 06:31:36
3,LSaczak,RT @officejjsmart: This is what it looks like ...,2022-06-21 23:59:49,2022-06-21 23:59:49
4,ReArtistron,RT @VivianAaron5: Check out this new framed pr...,2022-06-21 23:58:13,2022-06-21 23:58:13
...,...,...,...,...
9211,hasibabibi1,RT @97Maria_Hydra: @ZelenskyyUa @kajakallas Se...,2022-06-22 15:00:31,2022-06-22 15:00:31
9212,vanderschlong,@DSSdeltona @WhiteHouse @JoeBiden #Putin was h...,2022-06-22 14:59:20,2022-06-22 14:59:20
9213,Villain1982,@vonderleyen @EU_Commission What a pile of hor...,2022-06-22 14:58:11,2022-06-22 14:58:11
9214,PeaceLover07405,"@AZmilitary1 If we stop supporting #Ukraine, #...",2022-06-22 14:56:51,2022-06-22 14:56:51
9215,HilliusGlitch,Oh deary deary me! ðŸ˜¬\nI wonder if the Germans ...,2022-06-22 14:54:59,2022-06-22 14:54:59

In [15]:
df_merged2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   user    9216 non-null   object
 1   Tweet   9216 non-null   object
 2   Time    9216 non-null   datetime64[ns]
 3   Date    9216 non-null   datetime64[ns]
dtypes: datetime64[ns](2), object(2)
memory usage: 288.1+ KB